server:
  port: 8087
  context-path: /

provide:
  providePath: http://localhost:8088
logging:
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://wulang:1234@localhost:8761/eureka/
spring:
  application:
    name: consumer